"""Add encrypted_password column as String to User model

Revision ID: 0ab40caa2571
Revises: 75f042e57f1c
Create Date: 2024-10-27 20:28:21.087913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab40caa2571'
down_revision = '75f042e57f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('encrypted_password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('encrypted_password',
               existing_type=sa.String(length=500),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
