"""Add encrypted_password column to User model

Revision ID: 75f042e57f1c
Revises: 8cd2a968f57f
Create Date: 2024-10-27 20:24:00.790164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f042e57f1c'
down_revision = '8cd2a968f57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_password', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('encrypted_password')

    # ### end Alembic commands ###
